- index.md
Add content to the lesson's overview page:
- Introduce the lesson and its target audience.
- Add the prerequisites.
> DOC: Add content to the lesson's overview page

- _episodes/03-diffusion_tensor_imaging.md
Fix spelling and capitalize acronyms in lesson 03.
Remove trailing whitespaces.
> DOC: Fix spelling and capitalize acronyms in lesson 03

- _episodes/03-diffusion_tensor_imaging.md
Remove conflict-derived `git` traces in 03-DTI lesson.
The text was inadvertently left in commit
cca649ab754eece90a3136bdafb340987bf9a042
while rebasing on `master`.
> BUG: Remove conflict-derived `git` traces in 03-DTI lesson

- requirements.txt
Add `osfclient` to the requirements list to be able to download the necessary
data automatically.
> ENH: Add `osfclient` to the requirements list

- .github/workflows/build-test.yaml
The `.ipynb` notebooks are being run now with the updated path but running into failures. Probably because we need to include a step to download the dataset and cache it.
> FIX: Update ``.ipynb`` path and test on multiple Python versions

- reference.md
Add terms to glossary.
Adds the Carpentries [glossary component](https://carpentries.github.io/lesson-example/03-organization/index.html) as described [here](https://carpentries.github.io/lesson-example/reference.html) and resolves #44.
> DOC: Add terms to glossary

- README.md
Improve lesson information in `README`:
- Fix the imaging modality the lesson deals with.
- Improve the layout of the schedule/contents table.
- Fix a typo.
> DOC: Improve lesson information in `README`

- _extras/guide.md
Remove redundant instructor notes title.
Take advantage of the commit to adjust the heading levels.
> DOC: Remove redundant instructor notes title

- _includes/links.md
Fix `links.md` file comment tag syntax.
> BUG: Fix `links.md` file comment tag syntax

- _episodes/05-constrained_spherical_deconvolution.md
- code/05-constrained_spherical_deconvolution/05-constrained_spherical_deconvolution.ipynb
Remove unnecessary content from the CSD episode:
- Use the lesson data.
- Remove the `{: .language-python}` episode Markdown-specific markup from the
Jupyter notebook.
- Remove the episode Markdown-specific header from the Jupyter notebook.
- Move the data fetching code cell to the appropriate place in the Jupyter
notebook.
Take advantage of the commit to:
- Use the term "episode" to refer to the section.
- Add a caption to the last figure.
> ENH: Remove unnecessary content from the CSD episode

- _episodes/09-probabilistic_tractography.md
Improve syntax in prob tracking episode callout:  use the appropriate syntax to
highlight literal/command line blocks.
Fixes #61.
> DOC: Improve syntax in prob tracking episode callout

- _extras/figures.md
This repository had an older version of `_extras/figures.md`, which pre-dates the introduction of manual episode ordering for lessons. This PR brings that file up-to-date with the most recent version of the file, and should cause your Figures page to respect the order of episodes in the lesson.
> Manual episode order for Figures

- code/constrained_spherical_deconvolution/constrained_spherical_deconvolution.ipynb
Mark output cell as Markdown in CSD episode.
Fixes:
```
NameError Traceback (most recent call last)
<ipython-input-1-3cc994cc8588> in <module>
----> 1 (array([0.00159258, 0.00033926, 0.00033926]), 209.55229)
NameError: name 'array' is not defined
```
when running the cell.
> BUG: Mark output cell as Markdown in CSD episode

- _episodes/constrained_spherical_deconvolution.md
- _episodes/diffusion_tensor_imaging.md
- _episodes/introduction.md
- _episodes/local_tractography.md
- _episodes/preprocessing.md
- _episodes/probabilistic_tractography.md
Prefer the `{{ relative_root_path }}` placeholder to resolve figure paths.
Figures need to be located necessarily in a `fig` folder at the root level.
Using the placeholder allows to solve the paths without needing to use any
relative path and regardless of the location of the file containing it.
> STYLE: Prefer `{{ relative_root_path }}` to resolve figure paths

- _extras/discuss.md
Add discussion section about camera setup.
> DOC: Add discussion section about camera setup

- _episodes/tractography.md
Improve completeness of tractography method list.
Take advantage of the commit to re-order the method list chronologically.
> DOC: Improve the completeness of tractography method list

- _episodes/constrained_spherical_deconvolution.md
- _episodes/deterministic_tractography.md
- _episodes/diffusion_tensor_imaging.md
- _episodes/introduction.md
- _episodes/local_orientation_reconstruction.md
- _episodes/local_tractography.md
- _episodes/preprocessing.md
- _episodes/probabilistic_tractography.md
- _episodes/tractography.md
I noticed that your figures are not appearing on the lesson site. You are correctly using `relative_root_path` to specify the location of your image files, but this variable is only defined in the page if you `include` the `base_path.html` file in the page content. This PR adds that line to the beginning of every episode file, and should result in your images being displayed.
My next task is to document this in the lesson example...
> include base_path.html for relative_root_path

- code/probabilistic_tractography/probabilistic_tractography.ipynb
Fix probabilistic tractography notebook: the Jupyter engine was unable to parse
the notebook since it was missing some newline/end of line characters (`,`), and
thus did not constitute a valid JSON entity.
> BUG: Fix probabilistic tractography notebook

- code/deterministic_tractography/deterministic_tractography.ipynb
- code/deterministic_tractography/solutions/deterministic_tractography_solutions.ipynb
Fix deterministic tractography notebook: the Jupyter engine was unable to parse
the notebook since it was missing an end of line characters (`,`), and thus did
not constitute a valid JSON entity.
> BUG: Fix deterministic tractography notebook

- .github/workflows/build-test.yaml
Fix GitHub actions notebook test workflow
Fixes #31.
> ENH: Fix GitHub actions notebook test workflow

- 404.md
Bring 404 page from lesson example.
> ENH: Bring 404 page from lesson example

- utils/visualization_utils.py
Fix the anatomical slice figure sorting: the
`generate_anatomical_slice_views` method was returning the coronal anterior,
sagittal right and axial superior figures, but the
`generate_anatomical_slice_figure` method was mixing that order.
Take advantage of the commit to set the correct titles to the views.
This makes it consistent with the volume figures.
> BUG: Fix the anatomical slice figure sorting

- code/constrained_spherical_deconvolution/constrained_spherical_deconvolution.ipynb
Mark numeric cell as Markdown in CSD episode.
> STYLE: Mark numeric cell as Markdown in CSD episode

- _episodes/deterministic_tractography.md
- _episodes/diffusion_tensor_imaging.md
- code/deterministic_tractography/deterministic_tractography.ipynb
- code/diffusion_tensor_imaging/diffusion_tensor_imaging.ipynb
- code/diffusion_tensor_imaging/solutions/diffusion_tensor_imaging_solutions.ipynb
Call NiBabel `get_fdata()` instead of `get_data()`.
Given that we do not specify the `NiBabel` version in the requirements file, the
latest version will be used.
Fixes:
```
DeprecationWarning: get_data() is deprecated in favor of get_fdata(), which has
a more predictable return type. To obtain get_data() behavior going forward, use
numpy.asanyarray(img.dataobj).\n\n* deprecated from version: 3.0\n* Will raise
<class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 5.0\n  after
removing the cwd from sys.path.\n"
```
> ENH: Call NiBabel `get_fdata()` instead of `get_data()`

- .github/workflows/build-test.yaml
- setup.md
Added a single subject zip file to the OSF. Using `clone` clones the entire repository, which may take a while, while using `fetch` only allows you to download a single file at a time. 
Added instructions to use `fetch` to download and unzip this single subject zip, which contains all the preprocessed data for `sub-010006`
> DOC: Add info about downloading single subject from OSF

- .github/workflows/build-test.yaml
- setup.md
This should actually resolve #129 now. Previous `PYTHONPATH` included the `utils` directory which threw a `ModuleNotFound` when imported outside of parent directory given the way the code is currently setup. 
To avoid having to go through and update all of the paths, update the path to include the parent directory instead. Testing the updated path in jupyter seems to have worked.
> FIX: Update pythonpath

- _episodes/diffusion_tensor_imaging.md
- code/diffusion_tensor_imaging/diffusion_tensor_imaging.ipynb
- code/diffusion_tensor_imaging/solutions/diffusion_tensor_imaging_solutions.ipynb
Addresses previously missed comment about sentence structure and also missed `DIPY` capitalization in the Jupyter notebook.
@jhlegarreta you'll have to let me know what else is missed - hard for me to see the differences despite going through the notebooks and markdown file side-by-side.
> STY: Update DTI notebook

- .github/workflows/build-test.yaml
Noticed the latest CI run was unsuccessful after failing to remove the zip due to an incorrect path. This PR updates the path to remove the downloaded zip.
> FIX: Actions workflow - rm zip

- code/deterministic_tractography/solutions/deterministic_tractography_solutions.ipynb
Deterministic tractography solutions notebook was causing workflow to fail due to use of a local kernel. Reset it with this PR.
> FIX: Reset notebook kernel

- _episodes/constrained_spherical_deconvolution.md
- code/constrained_spherical_deconvolution/solutions/constrained_spherical_deconvolution_solutions.ipynb
Split apart the visualization part from the ODF computation part in the CSD
episode exercise.
Mark the visualization cell to be skipped in the tests.
Take advantage of the commit to provide an explanation to the result of the
exercise.
> ENH: Split apart visualization cell in CSD exercise

- setup.md
Fix unknown code block warning raised when running `make lesson-check-all`.
Fixes:
```
./setup.md:83: Unknown or missing code block type bash
./setup.md:92: Unknown or missing code block type bash
./setup.md:99: Unknown or missing code block type bash
./setup.md:105: Unknown or missing code block type bash
./setup.md:117: Unknown or missing code block type bash
./setup.md:124: Unknown or missing code block type bash
./setup.md:131: Unknown or missing code block type bash
./setup.md:140: Unknown or missing code block type bash
./setup.md:149: Unknown or missing code block type bash
./setup.md:156: Unknown or missing code block type bash
./setup.md:173: Unknown or missing code block type bash
./setup.md:184: Unknown or missing code block type bash
```
raised for example in: …
> STYLE: Fix unknown code block warning

- _includes/lesson_links.md
- _includes/links.md
Use a separate, lesson-specific links file.
> STYLE: Use a separate, lesson-specific links file

- README.md
- _episodes/constrained_spherical_deconvolution.md
- _episodes/deterministic_tractography.md
- _episodes/diffusion_tensor_imaging.md
- _episodes/introduction.md
- _episodes/preprocessing.md
- index.md
Limit line length in Markdown files to 80 characters.
Fixes most of the related warnings issued by the `make lesson-check-all`
command, e.g. in
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/runs/2438761253?check_suite_focus=true#step:16:18
> STYLE: Limit line length in Markdown files

- .github/workflows/build-test.yaml
I updated the "Build, test" workflow by removing the virtualenv creation step. I also set it to run only if changes are made to the `.ipynb` files
Checkout the last successful run [here](https://github.com/carpentries-incubator/SDC-BIDS-dMRI/actions/runs/817037226).
> FIX: Update Github Actions caching

- .github/workflows/build-test.yaml
I finally have this working in a separate test repository. The workflow ran successfully the first time. It re-ran a second time after a minor change to the notebook and the osf data was downloaded again.
> FIX: Update to pip install cache

- _episodes/diffusion_tensor_imaging.md
Use `inline` image class to display images within a paragraph.
> STYLE: Use `inline` image class

- _episodes/constrained_spherical_deconvolution.md
- _episodes/deterministic_tractography.md
- _episodes/diffusion_tensor_imaging.md
- _episodes/introduction.md
- _episodes/local_tractography.md
- _episodes/probabilistic_tractography.md
- _extras/discuss.md
Remove the unnecessary `img-responsive` class for images: rely on the
`Carpentries` `lesson.scss` `img` class to handle the necessary properties.
> STYLE: Remove the unnecessary `img-responsive` class for images

- utils/visualization_utils.py
Fix figure generation docstring:
- Fix the argument order.
- Fix the argument type for the varying argument number `*scenes` variable.
> DOC: Fix figure generation method docstring

- code/introduction/introduction.ipynb
- code/introduction/solutions/introduction_solutions.ipynb
Fix data location in non solution introduction notebook.
Fixes:
```
(...)
----> 8 layout = BIDSLayout("../../../data/ds000221", validate=False)
(...)
67     if not os.path.exists(root):
---> 68         raise ValueError("BIDS root does not exist: %s" % root)
(...)
ValueError: BIDS root does not exist: /home/runner/work/SDC-BIDS-dMRI/data/ds000221
```
reported in:
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/runs/3120044369?check_suite_focus=true#step:7:72
> BUG: Fix data location in non solution introduction notebook

- code/constrained_spherical_deconvolution/constrained_spherical_deconvolution.ipynb
Skip visualization cells in non-solution CSD notebook.
Fixes:
```
_ code/constrained_spherical_deconvolution/constrained_spherical_deconvolution.ipynb::Cell 4 _
Notebook cell execution failed
Cell 4: Timeout of 2000 seconds exceeded while executing cell. Failed to interrupt kernel in 5 seconds, so failing without traceback.
```
reported in:
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/runs/3140013883?check_suite_focus=true#step:7:109
> ENH: Skip visualization cells in non-solution CSD notebook

- _episodes/constrained_spherical_deconvolution.md
- _episodes/probabilistic_tractography.md
- code/constrained_spherical_deconvolution/constrained_spherical_deconvolution.ipynb
- code/constrained_spherical_deconvolution/solutions/constrained_spherical_deconvolution_solutions.ipynb
- code/probabilistic_tractography/probabilistic_tractography.ipynb
Update `DIPY` fiber response function method call.
Fixes:
```
DeprecationWarning: dipy.reconst.csdeconv.auto_response is deprecated,
Please use dipy.reconst.csdeconv.auto_response_ssst instead
* deprecated from version: 1.2
* Will raise <class 'dipy.utils.deprecator.ExpiredDeprecationError'> as of version: 1.4
response, ratio = auto_response(gtab, data, roi_radius=10, fa_thr=0.7)
/python3.8/site-packages/dipy/reconst/csdeconv.py:80:
UserWarning: Parameter `roi_radius` is now called `roi_radii` and can be an
array-like (3,). Parameters `fa_callable` and `return_number_of_voxels`
are not used anymore.
warnings.warn(msg, UserWarning)
```
Improve the explanation on the use of the method.
> ENH: Update `DIPY` fiber response function method call

- code/probabilistic_tractography/probabilistic_tractography.ipynb
Fix `DIPY` fiber response function method call parameter.
Fixes:
```
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_2383/1570612591.py in <module>
----> 1 response, ratio = auto_response_ssst(gtab, dwi_data, roi_radius=10, fa_thr=0.7)
2 sh_order = 2
3 csd_model = ConstrainedSphericalDeconvModel(gtab, response, sh_order=sh_order)
4 csd_fit = csd_model.fit(dwi_data, mask=seed_mask)
TypeError: auto_response_ssst() got an unexpected keyword argument 'roi_radius'
```
raised in
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/runs/3209541907?check_suite_focus=true#step:7:219
> BUG: Fix `DIPY` fiber response function method call parameter

- code/preprocessing/solutions/preprocessing_solutions.ipynb
Fix data paths in preprocessing episode solutions notebook.
Fixes:
```
----> 3 layout = BIDSLayout("../../data/ds000221", validate=False)
ValueError: BIDS root does not exist: /home/runner/work/SDC-BIDS-dMRI/SDC-BIDS-dMRI/code/data/ds000221
```
reported in:
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/runs/3251572017?check_suite_focus=true#step:13:120
> BUG: Fix data paths in preprocessing episode solutions notebook

- .github/workflows/build-test.yaml
Fix typo in `Build, test` workflow step name.
> DOC: Fix typo in `Build, test` workflow step name

- _episodes/preprocessing.md
- code/preprocessing.ipynb
Allow initial dot for BIDS extension entity.
Fixes:
```
FutureWarning: The 'extension' entity currently excludes the leading dot ('.').
As of version 0.14.0, it will include the leading dot.
To suppress this warning and include the leading dot,
use `bids.config.set_option('extension_initial_dot', True)`.
warnings.warn("The 'extension' entity currently excludes the leading dot ('.'). "
```
> ENH: Allow initial dot for BIDS extension entity

- binder/postBuild
This adds the pythonpath to make use of the functions in `utils`. Going to merge this in as merging to another branch that has necessary libraries.
> [ENH] export utils to PYTHONPATH

- README.md
- _extras/guide.md
- _includes/lesson_links.md
- setup.md
Switch to `JupyterLab`: change mentions in documentation from `Jupyter
Notebooks` to `JupyterLab`.
> ENH: Switch to `JupyterLab`

- _episodes/diffusion_tensor_imaging.md
@jhlegarreta following up from https://github.com/carpentries/carpentries-theme/issues/22#issuecomment-976865274, to enable KaTeX, `math: true` must be added to the yaml header for the episode page. Thanks!
> turn katex on

- .github/workflows/build-test.yaml
Remove Python package cache restore in GHA workflow. Using the cache is
being problematic every time the `Install Python requirements` step of
the GHA is modified. Although the cache is removed after 7 days if it is
not accessed, it is impractical to need to wait for 7 days when a change
to the above step is done,
https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy
and it might even be a show-stopper when multiple changes need to be
made and tested that depend on changes to he requirements:
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/runs/5434181049?check_suite_focus=true#step:6:12
Also, installing the Python dependencies is not the most lengthy step
when compared to installing `FSL`, which, according to …
> ENH: Remove Python package cache restore in GHA workflow

- requirements.txt
Pin `matplotlib` package version.
Fixes:
```
ImportError: cannot import name 'get_renderer' from 'matplotlib.tight_layout'
(/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/matplotlib/tight_layout.py)
```
raised at:
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/actions/runs/3298335648/jobs/5440315644#step:13:132
> ENH: Pin `matplotlib` package version

- .github/workflows/build-test.yaml
Update actions versions to use `Node.js 16`.
Fixes:
```
Node.js 12 actions are deprecated.
For more information see:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16: actions/cache, actions/checkout, actions/setup-python
```
raised for example in
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/actions/runs/3303231018
> ENH: Update actions versions to use `Node.js 16`

- requirements.txt
Update DIPY version to 1.4.1 and FURY to 1.7.1.
Fixes errors related to NumPy type discontinued types:
```
AttributeError: module 'numpy' has no attribute 'float'
```
and
```
AttributeError: module 'numpy' has no attribute 'bool'
```
Raised for example in:
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/actions/runs/3773484312/jobs/6414959616#step:13:102
and
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/actions/runs/3776245758/jobs/6419403735#step:13:191
Documentation:
https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations
> ENH: Update DIPY and FURY

- binder/environment.yml
Fix package dependency spec in `Binder` when using `pip`.
Fixes:
```
Installing pip dependencies: ...working... Pip subprocess error:
ERROR: Invalid requirement: 'pybids=0.14.0' (from line 1 of /home/jovyan/binder/condaenv.ulzt7wnj.requirements.txt)
Hint: = is not a valid operator. Did you mean == ?
Ran pip subprocess with arguments:
['/srv/conda/envs/notebook/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/jovyan/binder/condaenv.ulzt7wnj.requirements.txt', '--exists-action=b']
Pip subprocess output:
failed
CondaEnvException: Pip failed
time: 202.640
```
Raised in:
blob:https://mybinder.org/344f60b1-514e-4043-8d8e-95722289a9b1
(include the `blob` tag when accessing the URL)
> BUG: Fix package dependency spec in `Binder` when using `pip`

- .github/workflows/build-test.yaml
Clean up `FSL` installer download step:
- Change `FSL` installer download directory to separate it from the github workspace/code checkout directory.
- Remove the file once the installation has finished.
> ENH: Clean up `FSL` installer download step

- .github/workflows/build-test.yaml
Fix Ubuntu dependencies caching exception paths.
> BUG: Fix Ubuntu dependencies caching exception paths

- _episodes/introduction.md
- _episodes/preprocessing.md
Allow rendering LaTeX math syntax in introduction and preprocessing episodes.
Follow-up to commit 578080e5b971d397c9d7f99ff0469c318721d1cc.
> STYLE: Allow rendering LaTeX math syntax: intro and preproc episodes

- .github/workflows/build-test.yaml
Add Python 3.11 to the CI build matrix.
> ENH: Add Python 3.11 to the CI build matrix

- .github/workflows/build-test.yaml
Set up correctly branches filter in build, test GHA workflow file: use `branches` instead of `branch` to filter git branches.
Fixes:
```
Schema validation: Property 'branch' is not allowed
```
Relevant documentation:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#using-filters
> ENH: Set up correctly branches filter in build, test GHA workflow file

- .github/workflows/build-test.yaml
Fix `build, test` workflow action warnings linked to `Node.js`: bump `actions/cache` to `v4`, `actions/setup-python` to `v5`, and `actions/checkout` to `v4`.
Fixes:
```
Node.js 16 actions are deprecated.
Please update the following actions to use Node.js 20:
actions/cache@v3, actions/setup-python@v4, actions/checkout@v3.
For more information see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.i
```
raised for example in:
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/actions/runs/7910734041
> ENH: Fix `build, test` workflow actions warnings linked to `Node.js`

- episodes/diffusion_tensor_imaging.md
Remove spare backslash in LaTeX inequality sign.
Left behind in commit 925596e.
> BUG: Remove spare backslash in LaTeX inequality sign

- README.md
Fix website build deployment status badge workflow target after the transition to the Carpentries Workbench infrastructure.
> ENH: Fix website build deployment status badge workflow target

- episodes/introduction.md
Remove unnecessary backslashes in `Introduction` figure caption.
> ENH: Remove unnecessary backslashes in `Introduction` figure caption

- .github/workflows/build-test.yaml
Bump Github actions version in the `Build, test` workflow file.
Fixes:
```
Node.js 16 actions are deprecated.
Please update the following actions to use Node.js 20:
actions/cache@v3, actions/setup-python@v4, actions/checkout@v3.
For more information see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
raised for example in:
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/actions/runs/9655229240
> ENH: Bump Github actions versions

- binder/environment.yml
- requirements.txt
Require Numpy major version smaller than 2: with the recent release of Numpy 2 a number of dependencies have started to fail, so require Numpy major versions smaller than 2 until dependencies adapt to Numpy 2.0.
Fixes:
```
AttributeError  Traceback (most recent call last)
AttributeError: _ARRAY_API not found
```
reported for example in:
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/actions/runs/9655229240/job/26630796981#step:13:65
Numpy 2.0.0 release notice:
https://numpy.org/news/#numpy-200-released
> ENH: Require Numpy major version smaller than 2
