carpentries-incubator/SDC-BIDS-dMRI

- _episodes/03-diffusion_tensor_imaging.md
Add additional explanations to DTI scalar measures.
> DOC: Add additional explanations to DTI scalar measures

- index.md
> DOC: Fix typo in `index.md`

- _extras/guide.md
> DOC: Add instructor notes

- .github/workflows/build-test.yaml
- README.md
Add `GitHub Actions` CI builds for notebooks.
> ENH: Add `GitHub Actions` CI builds for notebooks

- .gitignore
Add `.idea` folder (JetBrains' project settings folder)  to `.gitignore`.
> ENH: Add `.idea` folder to `.gitignore`

- README.md
Fix `README` `GitHub Actions` badge: show the badge.
> ENH: Fix `README` `GitHub Actions` badge

- AUTHORS
- README.md
Attempt 2. Apologies, realized the other PR was updating a now (year?) out-of-date repo. This should just included changes to add @jhlegarreta  to both the maintainers and authors list!
> update author and maintainer list

- _episodes/02-preprocessing.md
- code/02-diffusion-preprocessing/02-diffusion-preprocessing.ipynb
- code/02-diffusion-preprocessing/solutions/02-diffusion-preprocessing_solutions.ipynb
Added the reference for QSIPrep with preprint doi - will need to be updated when published.
> DOC: Add reference for QSIPrep

- _episodes/05-constrained-spherical-deconvolution.md
- code/05-constrained-spherical-deconvolution/05-constrained-spherical-deconvolution.ipynb
Make the `FURY` screenshots be displayed inline.
> ENH: Make the `FURY` screenshots be displayed inline

- _config.yml
Add lesson information to config file.
> DOC: Add lesson information to config file

- _episodes/01-introduction_diffusion_data.md
Add missing HTML code closing tag.
> DOC: Add missing HTML code closing tag

- reference.md
Remove the unnecessary code environment for the glossary terms.
> BUG: Remove the unnecessary code environment for the glossary terms

- _extras/guide.md
- _includes/links.md
- setup.md
Add setup instructions.
Create the `links.md` file to host the links, and hence to avoid inconsistencies when using links across multiple files.
> DOC: Add setup instructions

- setup.md
Fix setup instructions file syntax.
> BUG: Fix setup instructions file syntax

- _episodes/04-diffusion_tensor_imaging.md
Update exercise solution to also use `ds000221` for dti episode
> MAINT: Update exercise solution

- _episodes/diffusion_tensor_imaging.md
Fix typo in citation author name.
Please delete this line and the text below before submitting your contribution.
> DOC: Fix typo in citation author name

- _extras/guide.md
Declare no reported problems in instructor notes.
> DOC: Declare no reported problems in instructor notes

- _extras/discuss.md
Add further aspects of dMRI to discussion.
> DOC: Add further aspects of dMRI to discussion

- _episodes/diffusion_tensor_imaging.md
- _episodes/introduction.md
- _includes/links.md
> FIX: Update image display in DTI lesson

- _extras/discuss.md
Add missing base path include.
> BUG: Add missing base path include

- _episodes/probabilistic_tractography.md
- code/probabilistic_tractography/probabilistic_tractography.ipynb
Use the right bvec file in prob tractography episode.
> BUG: Use the right bvec file in prob tractography episode

- _episodes/probabilistic_tractography.md
- code/probabilistic_tractography/probabilistic_tractography.ipynb
Comply with PEP 8:
- Remove unused imports.
- Add missing whitespaces around operator.
> STYLE: Comply with PEP 8

- _episodes/introduction.md
- code/introduction/solutions/introduction_solutions.ipynb
Lesson still needs some more updates but will do that in a separate PR.
Focus here is to have the solutions notebook running so that we can successfully save any cached items.
> FIX: Fix broken paths in intro notebook

- _episodes/constrained_spherical_deconvolution.md
- code/constrained_spherical_deconvolution/constrained_spherical_deconvolution.ipynb
Constrain the slices to be shown to three dimensions in the CSD episode given
that only three slices will be shown.
> ENH: Constrain the slices to be shown to three dimensions

- _episodes/probabilistic_tractography.md
- code/probabilistic_tractography/probabilistic_tractography.ipynb
Define the SH order at a single location.
> ENH: Define the SH order at a single location

- code/probabilistic_tractography/probabilistic_tractography.ipynb
Change SH  order in probabilistic tractography notebook.
Left behind in PR #103.
> ENH: Change SH  order in probabilistic tractography notebook

- code/constrained_spherical_deconvolution/constrained_spherical_deconvolution.ipynb
Remove empty cell from CSD notebook.
> ENH: Remove empty cell from CSD notebook

- .github/workflows/build-test.yaml
Increase the test workflow scheduled frequency.
> ENH: Increase the test workflow scheduled frequency

- .editorconfig
- .github/workflows/template.yml
- .github/workflows/website.yml
- .gitignore
- CODE_OF_CONDUCT.md
- Gemfile
- Makefile
- _includes/base_path.html
- _includes/links.md
- assets/css/lesson.scss
- bin/boilerplate/CONTRIBUTING.md
- bin/boilerplate/_config.yml
- bin/dependencies.R
- bin/generate_md_episodes.R
- bin/lesson_check.py
- bin/markdown_ast.rb
- bin/util.py
- bin/workshop_check.py
This brings in updates from the styles repository, including fixes to the 404 page (https://github.com/carpentries/styles/pull/578)
> Update styles 2021-04-20

- README.md
Add website build workflow status badge to `README`.
> ENH: Add website build workflow status badge to `README`

- code/constrained_spherical_deconvolution/solutions/constrained_spherical_deconvolution_solutions.ipynb
> ENH: Fix cell test skip command

- _extras/discuss.md
Prefer using `{{ relative_root_path }}` to resolve episode links.
> STYLE: Prefer using `{{ relative_root_path }}` to resolve episode links

- .github/workflows/build-test.yaml
Remove unnecessary whitespaces from `Build, test` workflow file.
> STYLE: Remove unnecessary whitespaces

- _episodes/constrained_spherical_deconvolution.md
- _episodes/local_tractography.md
- _episodes/probabilistic_tractography.md
Allow rendering LaTeX math syntax.
Fixes #160.
> STYLE: Allow rendering LaTeX math syntax

- .github/workflows/build-test.yaml
> ENH: Test non-solution notebooks

- .github/workflows/build-test.yaml
- ENH: Run GitHub Actions build-test workflow on PRs
- ENH: Update Python versions in CI build matrix
> ENH: Run GitHub actions build test workflow on PRs

- .github/workflows/build-test.yaml
> ENH: Install FSL and ANTs within GitHub Actions

- _episodes/diffusion_tensor_imaging.md
- _episodes/probabilistic_tractography.md
- code/diffusion_tensor_imaging.ipynb
- code/probabilistic_tractography.ipynb
> STYLE: Remove unused imports

- _episodes/probabilistic_tractography.md
Remove orphan character in Python code snippet.
> DOC: Remove orphan character in Python code snippet

- _extras/guide.md
> DOC: Add memory limitation notes

- _episodes/diffusion_tensor_imaging.md
Fix DTI episode radial diffusivity inline picture markup.
> STYLE: Fix DTI episode radial diffusivity inline picture markup

- .github/workflows/template.yml
- .github/workflows/website.yml
Updates the setup-python Github action to the latest major version
> Update setup-python version

- binder/environment.yml
Synchronize Binder environment package versions with requirements.
> ENH: Synchronize `Binder` environment package versions with requirements

- .github/workflows/build-test.yaml
Conform to current `FSL` installation instructions.
Pin the version to a recent one.
Documentation:
https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation/Linux
> ENH: Conform to current `FSL` installation instructions

- _episodes/preprocessing.md
- code/preprocessing.ipynb
- BUG: Fix FSL `eddy` command call 
- STYLE: Add line feed characters to preprocessing notebook
> BUG: Fix FSL `eddy` command

- .github/workflows/build-test.yaml
- ENH: Reuse environment variables for FSL and ANTS
- ENH: Clean cache memory of downloaded package files in GHA workflow
- ENH: Do not try to cache protected system folders
> ENH: Miscellaneous improvements to build, test GHA workflow

- _episodes/preprocessing.md
- code/preprocessing.ipynb
- DOC: Fix image alt text syntax in preprocessing episode markdown file
- ENH: Add the preprocessing images to the episode code
> DOC: Fix preprocessing episode b0 brainmask image syntax

- .github/scripts/setup_headless.sh
- .github/workflows/build-test.yaml
Add notebook run GitHub Actions workflow file, and the accompanying headless setup shell script.
Left behind by the Carpentries Workbench infrastructure automated transition tool in commits 560b5b4, and 6dab472.
> ENH: Add notebook run GitHub Actions workflow file
